export const PatientList = [
    {
      patientId: "U110278OTU23",
      name: "Dr. John Deo",
      gender: "male",
      age: "30",
      weight: "70 kg",
      blood_group: "O+",
      phone: "08012345678",
      email: "doctor@gmail.com",
      attendant_name: "Mrs. Jane Deo",
      attendant_phone: "08012345678",
      attendant_email: "attendant@gmail.com",
    },
    {
      patientId: "U110278OTU23",
      name: "Dr. John Deo",
      gender: "male",
      age: "30",
      weight: "70 kg",
      blood_group: "O+",
      phone: "08012345678",
      email: "doctor@gmail.com",
      attendant_name: "Mrs. Jane Deo",
      attendant_phone: "08012345678",
      attendant_email: "attendant@gmail.com",
    },
    {
      patientId: "U110278OTU23",
      name: "Dr. John Deo",
      gender: "male",
      age: "30",
      weight: "70 kg",
      blood_group: "O+",
      phone: "08012345678",
      email: "doctor@gmail.com",
      attendant_name: "Mrs. Jane Deo",
      attendant_phone: "08012345678",
      attendant_email: "attendant@gmail.com",
    },
    {
      patientId: "U110278OTU23",
      name: "Dr. John Deo",
      gender: "male",
      age: "30",
      weight: "70 kg",
      blood_group: "O+",
      phone: "08012345678",
      email: "doctor@gmail.com",
      attendant_name: "Mrs. Jane Deo",
      attendant_phone: "08012345678",
      attendant_email: "attendant@gmail.com",
    },
    {
      patientId: "U110278OTU23",
      name: "Dr. John Deo",
      gender: "male",
      age: "30",
      weight: "70 kg",
      blood_group: "O+",
      phone: "08012345678",
      email: "doctor@gmail.com",
      attendant_name: "Mrs. Jane Deo",
      attendant_phone: "08012345678",
      attendant_email: "attendant@gmail.com",
    },
    {
      patientId: "U110278OTU23",
      name: "Dr. John Deo",
      gender: "male",
      age: "30",
      weight: "70 kg",
      blood_group: "O+",
      phone: "08012345678",
      email: "doctor@gmail.com",
      attendant_name: "Mrs. Jane Deo",
      attendant_phone: "08012345678",
      attendant_email: "attendant@gmail.com",
    },
]